server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-c7i0iffxgdsevmxf.us.auth0.com/
          audiences: https://ecommerce-microservices

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
