server:
  port: 8082

spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:mysql://product-mysql:3306/product_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
