server:
  port: 8081

spring:
  datasource:
    # 'createDatabaseIfNotExist=true' will create the DB for you automatically
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: root  
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        # Spring Boot 3 automatically detects the correct MySQL dialect, 
        # but you can force it here if needed:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  tracing:
    sampling:
      probability: 1.0   # trace every request (perfect for learning)

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info
      
